### PR TITLE
Fix appendix section titles

### LINKED ISSUE #3: Issues with Appendix sections
The JMLR style contains the following `\appendix` redefinition
```
\renewcommand{\appendix}{\par
  \setcounter{section}{0}
  \setcounter{subsection}{0}
  \def\thesection{\Alph{section}}
\def\section{\@ifnextchar*{\@startsiction{section}{1}{\z@}{-0.24in}{0.10in}%
             {\large\bf\raggedright}}%
{\@startsiction{section}{1}{\z@}{-0.24in}{0.10in}
             {\large\bf\raggedright Appendix\ }}}}
```

The goal of the renewcommand above is to append "Appendix" at the beginning of appendix sections (for instance "A. My section" becomes "Appendix A. My section"). However, it is messing with section references (table of contents, links), as shown in the screenshot below (table of contents shown in a PDF reader).

image

### PR DESCRIPTION
**Pull request by dlej**
The example style file has appendix titles formatted as "Appendix A.", but the current `.sty` file only outputs "A." by default. This can't be fixed by packages like `appendix` or `titlesec` due to the custom sectioning of the `.sty` file. This patch modifies the section display when the `\appendix` command is run so that the appendix titles are displayed correctly.

### CODE REVIEW

**Comment by dlej** [comment]
This should the PDF referencing/table of contents issue in #3 as well, which was only resolved by removing the appendix title formatting.

**Comment by fabianp** [comment]
Thanks @dlej ! Do you mind submitting also the updated sample.pdf file? Thanks!

@akucukelbir : are you OK with this change?

**Comment by dlej** [comment]
@fabianp I have updated the `sample.pdf` file now. I also realized that `\NewCommandCopy` I had before was only supported by newer versions of LaTeX, so I replaced it with `\let` so that it works in older environments.

**Comment by fabianp** [comment]
Thanks. Looks good to me, but I'd like to have the LGTM of our production editor @akucukelbir before merging

**Comment by akucukelbir** [comment]
hi folks, sorry for the delay.

@dlej looks good at a quick glance! thank you!

@fabianp could you let me merge this when i have some time to update the production app? i need to keep both synced so i need a bit of time to coordinate both.

**Comment by fabianp** [comment]
hey @akucukelbir . Happy new year and gentle ping :-)

**Comment by fabianp** [comment]
hey @akucukelbir , any chance you could take a look into this? thanks!

**Pull request merged**
